# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RLWE.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='RLWE.proto',
  package='',
  serialized_pb=_b('\n\nRLWE.proto\",\n\nSampleCont\x12\x0e\n\x01\x61\x18\x01 \x02(\x0b\x32\x03.Rq\x12\x0e\n\x01\x62\x18\x02 \x02(\x0b\x32\x03.Kq\",\n\nSampleDisc\x12\x0e\n\x01\x61\x18\x01 \x02(\x0b\x32\x03.Rq\x12\x0e\n\x01\x62\x18\x02 \x02(\x0b\x32\x03.Rq\",\n\nSampleRLWR\x12\x0e\n\x01\x61\x18\x01 \x02(\x0b\x32\x03.Rq\x12\x0e\n\x01\x62\x18\x02 \x02(\x0b\x32\x03.Rq\"&\n\x02Rq\x12\t\n\x01m\x18\x01 \x02(\r\x12\t\n\x01q\x18\x02 \x02(\x04\x12\n\n\x02xs\x18\x03 \x03(\x12\"&\n\x02Kq\x12\t\n\x01m\x18\x01 \x02(\r\x12\t\n\x01q\x18\x02 \x02(\x04\x12\n\n\x02xs\x18\x03 \x03(\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SAMPLECONT = _descriptor.Descriptor(
  name='SampleCont',
  full_name='SampleCont',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='SampleCont.a', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='b', full_name='SampleCont.b', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=58,
)


_SAMPLEDISC = _descriptor.Descriptor(
  name='SampleDisc',
  full_name='SampleDisc',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='SampleDisc.a', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='b', full_name='SampleDisc.b', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=104,
)


_SAMPLERLWR = _descriptor.Descriptor(
  name='SampleRLWR',
  full_name='SampleRLWR',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='SampleRLWR.a', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='b', full_name='SampleRLWR.b', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=150,
)


_RQ = _descriptor.Descriptor(
  name='Rq',
  full_name='Rq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='m', full_name='Rq.m', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='q', full_name='Rq.q', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='xs', full_name='Rq.xs', index=2,
      number=3, type=18, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=152,
  serialized_end=190,
)


_KQ = _descriptor.Descriptor(
  name='Kq',
  full_name='Kq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='m', full_name='Kq.m', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='q', full_name='Kq.q', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='xs', full_name='Kq.xs', index=2,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=192,
  serialized_end=230,
)

_SAMPLECONT.fields_by_name['a'].message_type = _RQ
_SAMPLECONT.fields_by_name['b'].message_type = _KQ
_SAMPLEDISC.fields_by_name['a'].message_type = _RQ
_SAMPLEDISC.fields_by_name['b'].message_type = _RQ
_SAMPLERLWR.fields_by_name['a'].message_type = _RQ
_SAMPLERLWR.fields_by_name['b'].message_type = _RQ
DESCRIPTOR.message_types_by_name['SampleCont'] = _SAMPLECONT
DESCRIPTOR.message_types_by_name['SampleDisc'] = _SAMPLEDISC
DESCRIPTOR.message_types_by_name['SampleRLWR'] = _SAMPLERLWR
DESCRIPTOR.message_types_by_name['Rq'] = _RQ
DESCRIPTOR.message_types_by_name['Kq'] = _KQ

SampleCont = _reflection.GeneratedProtocolMessageType('SampleCont', (_message.Message,), dict(
  DESCRIPTOR = _SAMPLECONT,
  __module__ = 'RLWE_pb2'
  # @@protoc_insertion_point(class_scope:SampleCont)
  ))
_sym_db.RegisterMessage(SampleCont)

SampleDisc = _reflection.GeneratedProtocolMessageType('SampleDisc', (_message.Message,), dict(
  DESCRIPTOR = _SAMPLEDISC,
  __module__ = 'RLWE_pb2'
  # @@protoc_insertion_point(class_scope:SampleDisc)
  ))
_sym_db.RegisterMessage(SampleDisc)

SampleRLWR = _reflection.GeneratedProtocolMessageType('SampleRLWR', (_message.Message,), dict(
  DESCRIPTOR = _SAMPLERLWR,
  __module__ = 'RLWE_pb2'
  # @@protoc_insertion_point(class_scope:SampleRLWR)
  ))
_sym_db.RegisterMessage(SampleRLWR)

Rq = _reflection.GeneratedProtocolMessageType('Rq', (_message.Message,), dict(
  DESCRIPTOR = _RQ,
  __module__ = 'RLWE_pb2'
  # @@protoc_insertion_point(class_scope:Rq)
  ))
_sym_db.RegisterMessage(Rq)

Kq = _reflection.GeneratedProtocolMessageType('Kq', (_message.Message,), dict(
  DESCRIPTOR = _KQ,
  __module__ = 'RLWE_pb2'
  # @@protoc_insertion_point(class_scope:Kq)
  ))
_sym_db.RegisterMessage(Kq)


# @@protoc_insertion_point(module_scope)
